name: Update Space Shooter Game

on:
  schedule:
    - cron: '0 0 * * *'   # Runs every day (UTC time)
  workflow_dispatch:      # Allows manual run button

permissions:
  contents: write

jobs:
  update-game:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Game
        uses: czl9707/gh-space-shooter@v1
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          username: ${{ github.repository_owner }}
          output-path: game.gif
          strategy: random
          fps: 40
